name: 🐛 Bug Report
description: Report a bug to help us improve DeepEyeSniper
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of DeepEyeSniper are you using? (Check the bottom of the UI)
      placeholder: e.g. v1.0.10
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Windows
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Linux (Ubuntu)
    validations:
      required: true
